---
- hosts: all
  remote_user: vagrant
  sudo: yes
  tasks:
    - name: Install unzip
      apt: pkg=unzip state=latest update_cache=yes

    - name: Install MySQL client, server and related libraries
      apt: pkg={{ item }} state=latest
      with_items:
        - mysql-client
        - mysql-server
        - python-mysqldb

    - name: Install PHP and its modules
      apt: pkg={{ item }} state=latest
      with_items:
        - php5
        - php5-cli
        - php5-curl
        - php5-gd
        - php5-imagick
        - php5-mysql
        - php5-xmlrpc
        - phpmyadmin

    - name: Install Apache and its modules
      apt: pkg={{ item }} state=latest
      with_items:
        - apache2-mpm-prefork
        - libapache2-mod-php5

    - name: Activate mod_rewrite
      apache2_module: name=rewrite state=present

    - name: Start MySQL service
      service:
        name: "mysql"
        state: started
        enabled: yes

    - name: Setup MySQL root password
      mysql_user:
        name: "root"
        password: "mysql"
        host: "{{ item }}"
        state: present
      with_items:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost

    - name: Setup MySQL creds for root user
      template:
        src: "templates/my.cnf"
        dest: "/root/.my.cnf"
        owner: "root"
        mode: 0600

    - name: Delete blank MySQL users
      mysql_user:
        name: ""
        host: "{{ item }}"
        state: absent
      with_items:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost

    - name: Drop MySQL test database
      mysql_db: name=test state=absent

    - name: Drop WordPress database
      mysql_db: name=wordpress state=absent
      
    - name: Remove WP Installation
      file: name=/vagrant/wordpress state=absent
      
    - name: Setup empty database for WordPress
      mysql_db:
        name: "wordpress"
        encoding: "utf8"
        collation: "utf8_unicode_ci"
        state: "present"
        login_user: "root"
        login_password: "mysql"

    - name: Load inital dump for WordPress
      mysql_db: name=wordpress state=import target=/vagrant/ansible/templates/initial-wp4-wp4.dump.sql

    - name: Setup MySQL user for WordPress
      mysql_user:
        name: "wordpress"
        password: "wordpress"
        host: "localhost"
        priv: "wordpress.*:ALL"
        state: "present"

    - name: Put "vagrant" user in www-data group
      user:
        name: "vagrant"
        groups: "www-data"
        append: yes

    - name: Get latest WP
      get_url:
        url=https://wordpress.org/latest.zip 
        dest=/vagrant/wordpress.zip 
        validate_certs=no

    - name: Unzip WordPress
      unarchive: src=../wordpress.zip dest=/vagrant/

    - name: Symlink web root to unzipped WordPress
      file:
        src: "/vagrant/wordpress"
        dest: "/var/www/wordpress"
        state: "link"

    - name: Get WP Importer Plugin
      get_url:
        url=https://downloads.wordpress.org/plugin/wordpress-importer.0.6.1.zip
        dest=/vagrant/wordpress-importer.0.6.1.zip
        validate_certs=no

    - name: Unzip WordPress Importer
      unarchive: src=../wordpress-importer.0.6.1.zip dest=/vagrant/wordpress/wp-content/plugins/

    - name: Download flux-importer plugin
      get_url:
        url=https://github.com/netzwirt/wordpress-flux-importer/archive/master.zip
        dest=/vagrant/fluxcmsblog-importer.zip

    - name: Unzip FluxToWp Importer
      unarchive: src=../fluxcmsblog-importer.zip dest=/vagrant/wordpress/wp-content/plugins/

    - name: Move FluxToWp to plugins
      shell: mv /vagrant/wordpress/wp-content/plugins/wordpress-flux-importer-master/fluxcmsblog-importer/ /vagrant/wordpress/wp-content/plugins/fluxcmsblog-importer/        

    - name: Remove obsolete folder
      shell: rm -rf /vagrant/wordpress/wp-content/plugins/wordpress-flux-importer-master/

    - name: Remove WP Plugins and Downloaded Archives
      file: name={{ item }} state=absent
      with_items:
        - /vagrant/wordpress/wp-content/plugins/akismet
        - /vagrant/wordpress/wp-content/plugins/hello.php
        - /vagrant/wordpress.zip
        - /vagrant/fluxcmsblog-importer.zip
        - /vagrant/wordpress-importer.0.6.1.zip

    - name: Setup WP 
      shell: cp /vagrant/ansible/templates/wp-config.php /vagrant/wordpress/wp-config.php        

    - name: Copy virtual host setup over
      template: src=templates/wordpress.conf dest=/etc/apache2/sites-available/

    - name: Activate virtual host
      command: a2ensite wordpress

    - name: Deactivate default vhost
      command: a2dissite 000-default

    - name: Ensure Apache is running
      service: name=apache2 state=restarted enabled=yes
